### ISSUE TITLE
porting to google earth

### ISSUE THREAD

**Issue by wxwok** [iHamsterball/ingress-mission-map-plugin-fix-googlemap-china-offset#1]
Don't know how difficult is it to port this plugin to google earth? https://earth.google.com/web/. It will be great to make google earth works better in China.

**Comment by iHamsterball** [comment]
You could achieve your target if you managed to analyse and intercept all of the coordinate request functions during the drawing process of the map layer. However, Google Earth seems to use WebAssembly to handle interaction, which might add difficulty to analysing(I'm not sure, confirm by yourself).
